- PHPCI/Plugin/Email.php
Fatal error: Call to undefined method PHPCI\Helper\Email::setIsHtml() in ../Email.php on line 107
> Error in E-Mail-Plugin, typing error ?

- .gitignore
- PHPCI/Command/CreateAdminCommand.php
- PHPCI/Command/InstallCommand.php
- Tests/PHPCI/Command/CreateAdminCommandTest.php
- console
Simplified the create admin command a bit. 
Are there any plans to use the Symfony Validator component?
> Create admin command cleanup

- PHPCI/Plugin/PhpUnit.php
- PHPCI/Plugin/Wipe.php
Interpolate %PROJECT% etc in the Wipe plugin and in PHPUnit's coverage path
> Additional interpolate

- PHPCI/Helper/BuildInterpolator.php
- PHPCI/Plugin/Deployer.php
And set the default reason for Deployer to use it
> Added the commit message to the BuildInterpolator

- PHPCI/Languages/lang.ru.php
**Contribution Type**: Impovement
**Primary Area**: Russian translation
**Description of change**: Updated russian translation for Summary plugin section (added stage_broken and stage_fixed keys)
> Updated russian translation for Summary plugin section

- PHPCI/Plugin/Deployer.php
> Added branch and update_only parameters

- PHPCI/Controller/SettingsController.php
- PHPCI/Languages/lang.de.php
Contribution Type: improvement
Primary Area: front-end
Description of change: Updated German translation.
> Update German translation.

- PHPCI/Plugin/Email.php
Contribution Type: cosmetic
Link to Bug:
Added localization for email plugin log
> Added localization for email plugin log

- PHPCI/Controller/BuildStatusController.php
Contribution Type: new feature|cosmetic
Link to Bug:
Improved build status image (Added optional params for shield.io)
> Improved build status image (Added optional params for shield.io)

- PHPCI/Command/RunCommand.php
Contribution Type: feature/bugfix
Link to Intent to Implement: -
Link to Bug: -
Added debug mode for cron run-builds command
> Added debug mode for cron run-builds command

- PHPCI/Languages/lang.ru.php
Contribution Type: cosmetic
Link to Bug:
> edit ru translate

- PHPCI/Languages/lang.pt-br.php
- PHPCI/View/Settings/index.phtml
- PHPCI/View/layout.phtml
- public/assets/js/phpci.js
Contribution Type: bug fix | new feature
I began the translation into Portuguese, and at the same time put some javascript functions to self select the menus.
I made a small correction in layout breaks
> Improvements, fixes and new language started

- PHPCI/Migrations/20161214164202_database_fixes.php
Per https://github.com/Block8/PHPCI/pull/1223 and https://github.com/Block8/PHPCI/pull/1268
> Fix database issues

- PHPCI/Helper/User.php
> Check session value before use

- PHPCI/Languages/lang.pl.php
> Updated polish translation

- PHPCI/Controller/WebhookController.php
Add a new function to support svn webhook and create a build. Not supposed to affect any of the code.
> * Add new function to cover the svn project web hook and create a build.

- PHPCI/Languages/lang.fr.php
Just add some missing french translations ;)
> Add missing french translations

- PHPCI/Plugin/Util/TapParser.php
Link to Intent to Implement: N/A
Link to Bug: N/A
I came across an interesting glitch where in if a primary was skipped, and resulting child (@dependsOn), the tap parser considered the skipped child tests as failed tests. This adds the logic to ensure that those are considered passing.
> Applying Fixes For Skipped Tests Due To Depends

- PHPCI/Plugin/Deployer.php
Add the commit ID parameter to the deployer webhook
> [WIP] Add the commit ID parameter to the deployer webhook 

- PHPCI/Model/Build/GithubBuild.php
- PHPCI/Model/Build/RemoteGitBuild.php
Contribution Type: refactor
Link to Intent to Implement: N/A
Link to Bug: N/A
When working with pull requests on github, the pull request was assumed to be a public repository with proper access but not anything with a private repo. This updates it so that a private repo pull request can be used.
> GitHub private pull request
