PHPCI/View/layout.phtml, public/assets/css/AdminLTE-custom.css
My user name is to long and jumps to the next line.
Before:
After:
=> Fix username style in user panel block.

PHPCI/Application.php, PHPCI/Controller/SettingsController.php, PHPCI/Plugin/TechnicalDebt.php
=> Remove short array syntax to keep backwards compatibility with php5.3

PHPCI/Command/InstallCommand.php
This occurs commonly on Windows, but from my reading of the code it would also be a problem on other platforms if spaces were present (though this is less likely, due to different naming conventions).
It has been fixed by using escapeshellarg() on both of the paths used in the command.
Fixes #698, which I've just noticed has a similar solution suggested in one of the comments, but was closed without anyone actually implementing it.
=> Fixed the install script, which bails-out with an error if the PHPCI path contains spaces.

PHPCI/Plugin/Wipe.php
I was having problems due to $success being undefined if the directory does not exist, i.e. if it is a directory which is created by the build process and this is the first build
=> Preventing the wipe plugin failing due to an undefined variable

PHPCI/Plugin/TechnicalDebt.php
Just a small one to remove the output from the build log
This causes problems when finding TODO or FIXME in HTML files and potentially in JS files as the build log is not made HTML safe.
It also is inconsistent with the other plugins which don't pollute the build log with output unless they don't also have a UI plugin
=> Cleanup technical debt

PHPCI/Model/Build.php, PHPCI/Plugin/TechnicalDebt.php
A lot of other systems such as Travis, StyleCI and Codeclimate use a dotfile to hide to config, so I've tweaked the build process to check for a dotfile if phpci.yml doesn't exist
=> Adding support to check for .phpci.yml so the file can be 'hidden'

console.bat
This allows windows users not to have to type >`php console <command>`
=> adding windows batch file for console

PHPCI/Plugin/Util/TapParser.php, Tests/PHPCI/Plugin/Util/TapParserTest.php
**Contribution Type:** bugfix
**Primary Area:** TapParser (PHPUnit plugin)
**Description of change:**
Tap parser failed on valid phpunit output (No tests and enabled code coverage):
```
TAP version 13
Generating code coverage report in HTML format ... done
```
=> Fixed TapParser parse fail

PHPCI/Model/Build/GithubBuild.php
**Contribution Type:** bugfix
**Primary Area:** phpcpd plugin
**Description of change:**
On processing phpcpd output GithubBuild throw error:
```
Warning: Illegal offset type in .../GithubBuild.php line 224
```
=> Fixed GithubBuild::getDiffLineNumber method for correct phpcpd work

PHPCI/Plugin/Pdepend.php
This fixes problems with the xml output directory by the pdfepend module.  Before this fix, the pdepend module would check for "is_writable". But the php function "is_writeable" not only returns false when the directory is not writable, but also if the target directory does not exist at all. The error message given by phpci:pdepend-module is misleading in these cases.
I suggest to a) attempt to create the dir if it does not exist, and b) make the error message more explanatory in case the dir cannot be created or is not accessible.
=> Pdepend Module: make check for Pdepend output dir more robust.

PHPCI/Plugin/Mysql.php
Primary Area: plugins
Description of change: Implemented using the same changes mentioned here: https://www.phptesting.org/forums/topic/5-mysql-plugin-setup/
Allows you to specify a hostname for your mysql connection.  Not my original code just patching it into the current source and made a branchs/push for it.
(i.e. Created a new plugin named ToolX, used library X to implement, see link)
=> Contribution Type: improvement / new feature

PHPCI/View/Session.phtml
In Chrome (Android L), when you focus an input, the Block8 logo overrides the view.
See : http://s10.postimg.org/d5ffp7dwp/2015_06_30_07_57_03.png
=> Fixed a css issue with Block8 logo

PHPCI/Plugin/Codeception.php
The "optionally" is not true, the config file is now required.
=> Incorrect docblock

PHPCI/View/layout.phtml
This addresses some circumstances where there is no language file (like English), which had caused 404 Not Found error.
Reported in issue #999, #903.
=> Fix Datepicker Locale File Include

public/assets/js/build.js
This will allow the other non-hidden components to properly reflow on the page.
=> Fix Arrangement of Build Result Components

PHPCI/Plugin/SlackNotify.php
The attachment may not be useful in situations where you customise the message such as using a message in success, failure, fixed or broken rather than complete. For instance you may specifically mention "the build is broken!" so you don't need the attachment repeating it
=> Add the ability to hide the slack attachment

PHPCI/Plugin/PhpCsFixer.php
Update the PhpCsFixer plugin to work with the latest version of php-cs-fixer.
Also added the `--dry-run` option as it does not need to apply the change in the build directory.
This fixes https://github.com/Block8/PHPCI/issues/833
=> Update PhpCsFixer plugin

PHPCI/Controller/SettingsController.php
Primary Area: front-end
Description of change: Changed the default value of the language select on the settings page.
Description of solution: The default value is now the current language (before: English). The commit 942127f fixed the same bug on the user profile page.
=> Fixes small bug with language select on the settings page.

PHPCI/Plugin/Util/TestResultParsers/Codeception.php
Whenever a codeception test finishes with an error the test fails but is not counted as a  failure, it is counted as  an error in the report.xml file.  This makes the test  appear  green in the  phpci  UI and it should be red (because in the end the test failed).
This makes hard to test if the codeception plugin is working as expected because even when it fails all the test appear as they passed.
See this image, all the tests passed but the codeception status is marked as failed: 
In this PR I make the plugin be aware of  the errors not just of the failures.
=> Support for codeception errors

PHPCI/Builder.php
Contribution Type: **bug fix**
Primary Area: **builder**
Link to Bug: #1185 
Description of change: 
Complete is always executed after test and setup even when an exception is caught
Description of solution: 
The "complete" stage execution has been moved to a finally block in order to be executed no matter the result of setup and test stages.
=> [FIX] #1185 Running Complete stage even on Exception catch.

PHPCI/Plugin/PhpCpd.php
Contribution Type: refactor
Link to Bug:
The 'standard' option is unused in the PhpCpd plugin, and does not actually make sense for copy-paste-detection.
If this change is merged, the wiki page at https://github.com/block8/phpci/wiki/PHP-Copy-Paste-Detector-Plugin also needs to be updated.
=> Removed unused 'standard' option for PhpCpd plugin

PHPCI/Model/Build.php
Link to Intent to Implement: _N/A_
Link to Bug: https://github.com/Block8/PHPCI/issues/1187
Added a test on type of the build location. Depending on whether it is a directory or a symlink, the appropriate command is used to remove the location, the appropriate command is used to remove it, when the build is complete.
=> Fixed: Incorrect build removal if prefer_symlink is used #1187 

Tests/PHPCI/Helper/MailerFactoryTest.php, Tests/PHPCI/Model/BuildTest.php, Tests/PHPCI/Model/ProjectTest.php, Tests/PHPCI/Plugin/EmailTest.php, Tests/PHPCI/Service/BuildServiceTest.php, Tests/PHPCI/Service/ProjectServiceTest.php, Tests/PHPCI/Service/UserServiceTest.php
Link to Bug: [https://github.com/Block8/PHPCI/issues/1250](url)
- [*] I have read and understood the [contributing guidelines](/.github/CONTRIBUTING.md)?
- [*] I have checked that another pull request for this purpose does not exist.
- [*] I have considered, and confirmed that this submission will be valuable to others.
- [*] I have created or updated the relevant documentation for this change on the PHPCI Wiki.
- [*] Do the PHPCI tests pass?
Removed the @covers PHPUnit::execute declaration - no such thing exists in the code and code coverage testing will not finish otherwise.
=> Removing PHPUnit::execute Coverage Tags

PHPCI/Languages/lang.nl.php
Link to Intent to Implement: -
Link to Bug: -
The Dutch language file was missing keys, I added them from the English one, and translated the texts.
=> Added and translated missing key/value pairs in Dutch language file

PHPCI/Migrations/20160310132732_brach_column_length.php, PHPCI/Model/Base/BuildBase.php, PHPCI/Model/Base/ProjectBase.php
Sometimes it happened to me that I have longer branch name and PHPCI then cannot run tests (because of 50 characters limit on branch name).
=> Branch name in build table extended to 250 characters

composer.json
Contribution Type: bug fix / cosmetic
Detailed description of change: stop suggesting deprecated package
=> "friendsofphp/php-cs-fixer" instead of "fabpot/php-cs-fixer"

PHPCI/Plugin/PhpParallelLint.php
Contribution Type: new feature
Link to Bug: https://github.com/Block8/PHPCI/issues/1339
Add the option to pass the short tags (-s) argument to PHP Parallel Lint so that files using PHP Short Tags can be linted.
=> PHP-Parallel-Lint shorttags option

PHPCI/Controller/ProjectController.php, PHPCI/View/Project/view.phtml
Changes:
.- ProjectController::build: now also checks GET-vars for chosen branch name
.- Project/view: changed link on "build now": when a different branch is chosen, then send it through GET-vars, so slashes are not a problem
Link to Bug:
In Git, slashes are allowed in branch names, but when such a branch name is sent in the URL, Apache sends a 404 automatically, unless the AllowEncodedSlashes directive is set.
A solution is to send that variable as GET-var, so instead of /project/build/2/feature%2ffoo%2fbar, we use /project/build/2?branch=feature%2ffoo%2fbar.
Changes:
.- …
=> Bugfix: slash in branch name gives 404

PHPCI/Controller/ProjectController.php
ProjectController::build(): Moved the check on whether the project could be found up: no point in trying to get a list of branches of a project that doesn't even exist.
Contribution Type: refactor
Link to Intent to Implement: -
Link to Bug: -
Moved the check on whether the project could be found up: no point in trying to get a list of branches of a project that doesn't even exist.
=> ProjectController::build(): Moved the check on project

PHPCI/Helper/BaseCommandExecutor.php
Link to Intent to Implement: N/A
Link to Bug: N/A
When running on a 7.0 repo, I found that it the phpunit test would hang indefinately. When I ran the command directly in the command line, the command ran but died instantly. After a score of R&D, I finally learned that proc_open has a bug in it where if there is a ton of output on both stdout and stderr at the same time, a dead-lock occurs where one is effectively waiting on the other to finish. This change fixes that converting the processing to be non-blocking and instead relying on PHP to check the status. This bypasses the dead-lock and allows the code …
=> Proc Open deadlock

PHPCI/Plugin/PhpCpd.php
Problem with plugin: it sends the wrong command to ignore the files. When we ignore
directory, we use --exclude path/dir_1 --exclude path/dir_2 --exclude path/dir_3
everything works correctly but when we want to exclude file - PhpCpd.php
sends command like --names-exclude path/file_1 --names-exclude path/file_2
--names-exlcude path/file_3 and files will be scanned for copy/past, to ignore all three file we have to use command like --names-exclude file_1,file_2,file_3 without paths.
Contribution Type: bug fix 
=> problem with plugin PhpCpd

PHPCI/Model/Build/RemoteGitBuild.php
Detailed description of change: 
Put the branch value into quotes. So special chars like hash (#) in branch names will not effect the git clone command.
=> Fixes issue with branches that start with a hash

PHPCI/Plugin/PhpParallelLint.php
Contribution Type: bug fix 
Link to Bug:
The changes made in https://github.com/Block8/PHPCI/pull/1290 checks that the extensions passed in from config are a comma delimited string, but it only allowed one or two extensions.
php would be okay
php, html would be okay
php, html, phtml would be considered to not be valid.
This pull request fixes that.
=> Better regex (allow more than two extensions)

PHPCI/Controller/WebhookController.php
Enables for example a maintainer to run a daily build of their project,
whether a change has been made or not. The rebuild parameter is made
fully optional.
Contribution Type: new feature
An optional parameter `rebuild` has been added to `WebhookController::createBuild`. This allows a maintainer to use the git webhook to start a rebuild of their project. At our project we want an automatic daily build of the project and this feature supports it.
In `WebhookController::git` the parameter `rebuild` can be read, where it is `false` if no parameter has been given. The parameter `$rebuild` is then passed to …
=> Add support for rebuild on Git webhook
